dist: bionic
language: python
sudo: required
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y librrd-dev
install: python setup.py install
script: nosetests
